# This file contains the configuration for the GitHub Actions workflow that will deploy the infrastructure using Terraform
name: Deploy Infrastructure with Terraform

# Define when the workflow should be triggered
on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    # Define the environment variables
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    # Define the steps that will be executed
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set Up Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.9.8
        
        - name: Terraform Init
          working-directory: ./terraform
          run: terraform init
          
        - name: Terraform Validate
          working-directory: ./terraform
          run: terraform validate
        
        - name: Terraform Plan
          working-directory: ./terraform
          run: terraform plan
        
        - name: Terraform Apply
          working-directory: ./terraform
          run: terraform apply -auto-approve